/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAngelaList, IAngelaListInterface } from "../IAngelaList";

const _abi = [
  {
    inputs: [],
    name: "merkleRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAngelaList__factory {
  static readonly abi = _abi;
  static createInterface(): IAngelaListInterface {
    return new utils.Interface(_abi) as IAngelaListInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAngelaList {
    return new Contract(address, _abi, signerOrProvider) as IAngelaList;
  }
}
