/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICTest, ICTestInterface } from "../ICTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICTest__factory {
  static readonly abi = _abi;
  static createInterface(): ICTestInterface {
    return new utils.Interface(_abi) as ICTestInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ICTest {
    return new Contract(address, _abi, signerOrProvider) as ICTest;
  }
}
