/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AngelaListInterface extends ethers.utils.Interface {
  functions: {
    "merkleRoot()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;

  events: {
    "merkleRootUpdated(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "merkleRootUpdated"): EventFragment;
}

export type merkleRootUpdatedEvent = TypedEvent<
  [string] & { _merkleRoot: string }
>;

export class AngelaList extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AngelaListInterface;

  functions: {
    merkleRoot(overrides?: CallOverrides): Promise<[string]>;
  };

  merkleRoot(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    merkleRoot(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "merkleRootUpdated(bytes32)"(
      _merkleRoot?: null
    ): TypedEventFilter<[string], { _merkleRoot: string }>;

    merkleRootUpdated(
      _merkleRoot?: null
    ): TypedEventFilter<[string], { _merkleRoot: string }>;
  };

  estimateGas: {
    merkleRoot(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    merkleRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
